//users
export const FETCH_USERS_LIST_REQUEST = "FETCH_USERS_LIST_REQUEST"
export const FETCH_USERS_LIST_REQUEST_FAIL = "FETCH_USERS_LIST_REQUEST_FAIL"
export const FETCH_USERS_LIST_REQUEST_SUCCESS = "FETCH_USERS_LIST_REQUEST_SUCCESS"
